name: Build Pipeline

on:
  push:
    branches: [ master ]
  
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.2
    
    - name: Install dependencies
      run: nuget restore CastIntoGenerator.sln
      
    - name: Build
      run: MSBuild.exe CastIntoGenerator.sln -property:Configuration=Release
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Binario
        path: CastIntoGenerator/bin/Release/CastIntoGenerator.exe
      
 
