name: Publish Pipeline

on:
  push:
    branches: [ Release ]
  
jobs:
  build:
    
    runs-on: windows-latest
    outputs:
      build_number: ${{ steps.buildnumber.outputs.build_number }}
    env: 
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
    - uses: actions/checkout@v2
   
    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v2 
      with:
        token: ${{secrets.github_token}}
        prefix: vTwo
         
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.2
    
    - name: Install dependencies
      run: nuget restore CastIntoGenerator.sln
      
    - name: Build
      run: MSBuild.exe CastIntoGenerator.sln -property:Configuration=Release
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Binary
        path: CastIntoGenerator/bin/Release/CastIntoGenerator.exe
    
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: 2.${{ steps.buildnumber.outputs.build_number }}
        release_name: Release 2.${{ steps.buildnumber.outputs.build_number }}
        body: |
          Version 2.${{ steps.buildnumber.outputs.build_number }} 
          ${{github.event.head_commit.message}}
        draft: false
        prerelease: false
        
    - name: Upload Release Asset
      id: upload-exe 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: CastIntoGenerator/bin/Release/CastIntoGenerator.exe
        asset_name: CastIntoGenerator.exe
        asset_content_type: application/vnd.microsoft.portable-executable
        
    - name: Upload Release Asset
      id: upload-T4 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: CastIntoGeneratorBiz/T4Template.tt
        asset_name: T4Template.tt
        asset_content_type: text
       
        
    
    
      
 
